# Generated by Django 4.0.2 on 2025-06-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_guild_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'race')},
        ),
    ]
